using System.Text;
using M365Permissions.Engine.Models;

namespace M365Permissions.Engine.Export;

/// <summary>
/// Exports permission entries to CSV format.
/// </summary>
public sealed class CsvExporter
{
    // Branded header comment — reports travel to execs, the module doesn't ($3).
    private const string BrandComment =
        "# Generated by M365Permissions — for continuous, hosted scanning see https://m365permissions.com";

    private const string Header =
        "Risk Level,Risk Reason,Target Path,Target Type,Target ID," +
        "Principal Entra ID,Principal UPN,Principal System ID,Principal Name," +
        "Principal Type,Role,Through,Access Type,Tenure," +
        "Parent ID,Start Date,End Date,Created,Modified";

    public byte[] Export(IReadOnlyList<PermissionEntry> entries)
    {
        using var ms = new MemoryStream();
        using (var writer = new StreamWriter(ms, new UTF8Encoding(encoderShouldEmitUTF8Identifier: true), leaveOpen: true))
        {
            writer.WriteLine(BrandComment);
            writer.WriteLine(Header);
            foreach (var e in entries) writer.WriteLine(FormatRow(e));
        }
        return ms.ToArray();
    }

    /// <summary>
    /// Stream a CSV by pulling pages from <paramref name="fetchPage"/> (which returns the next
    /// batch of rows after a given id) so the full result set is never materialised at once (P3).
    /// </summary>
    public byte[] ExportPaged(Func<long, List<PermissionEntry>> fetchPage)
    {
        using var ms = new MemoryStream();
        using (var writer = new StreamWriter(ms, new UTF8Encoding(encoderShouldEmitUTF8Identifier: true), leaveOpen: true))
        {
            writer.WriteLine(BrandComment);
            writer.WriteLine(Header);
            long afterId = 0;
            while (true)
            {
                var page = fetchPage(afterId);
                if (page.Count == 0) break;
                foreach (var e in page)
                {
                    writer.WriteLine(FormatRow(e));
                    if (e.Id > afterId) afterId = e.Id;
                }
            }
        }
        return ms.ToArray();
    }

    private static string FormatRow(PermissionEntry e) => string.Join(",",
        Escape(e.RiskLevel), Escape(e.RiskReason),
        Escape(e.TargetPath), Escape(e.TargetType), Escape(e.TargetId),
        Escape(e.PrincipalEntraId), Escape(e.PrincipalEntraUpn),
        Escape(e.PrincipalSysId), Escape(e.PrincipalSysName),
        Escape(e.PrincipalType), Escape(e.PrincipalRole),
        Escape(e.Through), Escape(e.AccessType), Escape(e.Tenure),
        Escape(e.ParentId), Escape(e.StartDateTime),
        Escape(e.EndDateTime), Escape(e.CreatedDateTime),
        Escape(e.ModifiedDateTime));

    private static string Escape(string value)
    {
        if (string.IsNullOrEmpty(value)) return "\"\"";
        if (value.Contains('"') || value.Contains(',') || value.Contains('\n') || value.Contains('\r'))
            return $"\"{value.Replace("\"", "\"\"")}\"";
        return $"\"{value}\"";
    }
}
